### ISSUE TITLE
Can't modify my gnome

### ISSUE THREAD

**Issue by lucas-bernardino** [GabrielTenma/dotfiles-gnm#8]
Hello. The changes you've made to your desktop are really good and I wanted to get this modifications to my gnome as well. I'm new to Linux and I'm having some difficulties in applying this changes. I did the git clone on your repo and I also entered the commands you've mentioned on my terminal. But some changes didn't work out as it should. I wanted to get the same "widgets" as those that are in your top screen, like temperature, the day and the song being played and I also wanted to get that bar notification on your top right corner.

**Comment by GabrielTenma** [comment]
apologize for that, i forgot mention list installed my gnome extension list

make sure you have been installed gnome shell integration, here for chrome: https://chrome.google.com/webstore/detail/gnome-shell-integration/gphhapmejobijbbhgpjhcjognlahblep

then open: https://extensions.gnome.org/
to check installed extension can check here: https://extensions.gnome.org/local/

search those listed extension
make sure those extension been installed:
++ mandatory to install
- ArcMenu :: https://extensions.gnome.org/extension/3628/arcmenu/ (left corner menu mod)
- Aylur's Widgets :: https://extensions.gnome.org/extension/5338/aylurs-widgets/ (add additional menu on top mod)
- Burn my windows :: https://extensions.gnome.org/extension/4679/burn-my-windows/ (window animation mod)
- Compiz alike magic lamp effect :: https://extensions.gnome.org/extension/3740/compiz-alike-magic-lamp-effect/ (fix glitch minimize gnome effect)
- Dash to dock :: https://extensions.gnome.org/extension/307/dash-to-dock/ (add dock)
- One window wonderland :: https://extensions.gnome.org/extension/5696/one-window-wonderland/ (window gaps when maximize)
- OpenWeather :: https://extensions.gnome.org/extension/750/openweather/ (weather indicator)
- Top bar organizer :: https://extensions.gnome.org/extension/4356/top-bar-organizer/ (organize top menu)
- Useless gaps :: https://extensions.gnome.org/extension/4684/useless-gaps/ (window gaps too)

++ optional
- Caffeine :: https://extensions.gnome.org/extension/517/caffeine/ (pause screen timeout)
- AATWS - Advanced Alt-Tab Window Switcher :: https://extensions.gnome.org/extension/4412/advanced-alttab-window-switcher/ (alt tab mod)
- Text scaler :: https://extensions.gnome.org/extension/1018/text-scaler/ (font scaling + listed to top menu)

after installed those extension, configure those extension too

[video] here how to configure those extension: https://drive.google.com/file/d/1q0XwtoJShAm0K07BT9JiV5Xkzt6iaiFD/view?usp=sharing

**Comment by GabrielTenma** [comment]
here how to configure those extension: https://drive.google.com/file/d/1e1tV4NE63jmZjHC-FoiWNWrepUv6QKeQ/view?usp=sharing

**Comment by lucas-bernardino** [comment]
Thanks a lot for your time and help.
